services:
  site:
    image: nginx:alpine
    container_name: arte-na-cura-site
    volumes:
      - ./site:/usr/share/nginx/html:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.artenacura.rule=Host(`dev.artenacura.com`)"
      - "traefik.http.routers.artenacura.entrypoints=websecure"
      - "traefik.http.routers.artenacura.tls.certresolver=letsencrypt"
